my_string = input("Напишите фразу ")
print ("В нем использовано ", len(my_string), " символов.")
print (my_string.upper())
print (my_string.lower())
print (my_string.replace(" ", ""))
print (my_string [-1])